
page_file_test:  page_file_test.cpp HtmlTags.h HtmlTags.cpp HtmlParser.h page_file_test.cpp page_data.h page_data.cpp
	g++ --std=c++17 -g page_file_test.cpp HtmlTags.cpp page_data.cpp -o page_file_test

clean:
	rm -f page_file_test
